#############################################################################
# Makefile for building: displayctl
# Generated by qmake (2.01a) (Qt 4.7.1) on: ?? 3? 13 07:40:51 2023
# Project:  displayctl.pro
# Template: app
# Command: /opt/qt-4.7.1/bin/qmake -o Makefile displayctl.pro
#############################################################################

####### Compiler, tools and options

CC            = arm-linux-gcc
CXX           = arm-linux-g++
DEFINES       = -DQT_DLL -DQWT_DLL -DQT_DEBUG -DQT_NO_DEBUG -DQT_QT3SUPPORT_LIB -DQT3_SUPPORT -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/opt/qt-4.7.1/mkspecs/qws/linux-arm-g++ -I. -I/opt/qt-4.7.1/include/QtCore -I/opt/qt-4.7.1/include/QtNetwork -I/opt/qt-4.7.1/include/QtGui -I/opt/qt-4.7.1/include/Qt3Support -I/opt/qt-4.7.1/include -I$(QTDIR)/include/QtGui -I$(QTDIR)/include/QtCore -IQwt-6.0.0/include -I. -I.
LINK          = arm-linux-g++
LFLAGS        = -Wl,-O1 -Wl,-rpath,/opt/qt-4.7.1/lib
LIBS          = $(SUBLIBS)  -L/opt/qt-4.7.1/lib -L$(QTDIR) -L/usr/local/tslib/lib -L/opt/qt-4.7.1/lib -lqwt6 -lQt3Support -lQtSql -lQtXml -lQtGui -lQtNetwork -lQtCore -lpthread 
AR            = arm-linux-ar cqs
RANLIB        = 
QMAKE         = /opt/qt-4.7.1/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = arm-linux-strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		mainwindow.cpp \
		logindlg.cpp \
		adjcoefdlg.cpp \
		chainsetdlg.cpp \
		thresholdsetdlg.cpp \
		gpiodatarecvthread.cpp \
		gpiorw.cpp \
		tempermonitorWidget.cpp \
		faultcondWidget.cpp \
		runningstatusWidget.cpp \
		md5encode.cpp \
		hiscurveWidget.cpp \
		plotuserclass.cpp \
		passwordsetdlg.cpp \
		invalidsetdlg.cpp \
		inifileparse.cpp \
		dcsetdlg.cpp \
		CANdatarw.cpp \
		keyboarddlg.cpp \
		hisCurvePlot.cpp \
		mylineedit.cpp \
		gainsetdlg.cpp \
		judgeprotection.cpp \
		countdownWidget.cpp \
		basicparasetdlg.cpp \
		syssetdlg.cpp \
		datareadthread.cpp \
		newadjdlg.cpp moc_mainwindow.cpp \
		moc_logindlg.cpp \
		moc_adjcoefdlg.cpp \
		moc_chainsetdlg.cpp \
		moc_thresholdsetdlg.cpp \
		moc_tempermonitorWidget.cpp \
		moc_faultcondWidget.cpp \
		moc_runningstatusWidget.cpp \
		moc_hiscurveWidget.cpp \
		moc_plotuserclass.cpp \
		moc_passwordsetdlg.cpp \
		moc_invalidsetdlg.cpp \
		moc_dcsetdlg.cpp \
		moc_keyboarddlg.cpp \
		moc_hisCurvePlot.cpp \
		moc_mylineedit.cpp \
		moc_gainsetdlg.cpp \
		moc_countdownWidget.cpp \
		moc_basicparasetdlg.cpp \
		moc_syssetdlg.cpp \
		moc_newadjdlg.cpp
OBJECTS       = main.o \
		mainwindow.o \
		logindlg.o \
		adjcoefdlg.o \
		chainsetdlg.o \
		thresholdsetdlg.o \
		gpiodatarecvthread.o \
		gpiorw.o \
		tempermonitorWidget.o \
		faultcondWidget.o \
		runningstatusWidget.o \
		md5encode.o \
		hiscurveWidget.o \
		plotuserclass.o \
		passwordsetdlg.o \
		invalidsetdlg.o \
		inifileparse.o \
		dcsetdlg.o \
		CANdatarw.o \
		keyboarddlg.o \
		hisCurvePlot.o \
		mylineedit.o \
		gainsetdlg.o \
		judgeprotection.o \
		countdownWidget.o \
		basicparasetdlg.o \
		syssetdlg.o \
		datareadthread.o \
		newadjdlg.o \
		moc_mainwindow.o \
		moc_logindlg.o \
		moc_adjcoefdlg.o \
		moc_chainsetdlg.o \
		moc_thresholdsetdlg.o \
		moc_tempermonitorWidget.o \
		moc_faultcondWidget.o \
		moc_runningstatusWidget.o \
		moc_hiscurveWidget.o \
		moc_plotuserclass.o \
		moc_passwordsetdlg.o \
		moc_invalidsetdlg.o \
		moc_dcsetdlg.o \
		moc_keyboarddlg.o \
		moc_hisCurvePlot.o \
		moc_mylineedit.o \
		moc_gainsetdlg.o \
		moc_countdownWidget.o \
		moc_basicparasetdlg.o \
		moc_syssetdlg.o \
		moc_newadjdlg.o
DIST          = /opt/qt-4.7.1/mkspecs/common/g++.conf \
		/opt/qt-4.7.1/mkspecs/common/unix.conf \
		/opt/qt-4.7.1/mkspecs/common/linux.conf \
		/opt/qt-4.7.1/mkspecs/common/qws.conf \
		/opt/qt-4.7.1/mkspecs/qconfig.pri \
		/opt/qt-4.7.1/mkspecs/features/qt_functions.prf \
		/opt/qt-4.7.1/mkspecs/features/qt_config.prf \
		/opt/qt-4.7.1/mkspecs/features/exclusive_builds.prf \
		/opt/qt-4.7.1/mkspecs/features/default_pre.prf \
		/opt/qt-4.7.1/mkspecs/features/release.prf \
		/opt/qt-4.7.1/mkspecs/features/default_post.prf \
		/opt/qt-4.7.1/mkspecs/features/warn_on.prf \
		/opt/qt-4.7.1/mkspecs/features/qt.prf \
		/opt/qt-4.7.1/mkspecs/features/unix/thread.prf \
		/opt/qt-4.7.1/mkspecs/features/moc.prf \
		/opt/qt-4.7.1/mkspecs/features/resources.prf \
		/opt/qt-4.7.1/mkspecs/features/uic.prf \
		/opt/qt-4.7.1/mkspecs/features/yacc.prf \
		/opt/qt-4.7.1/mkspecs/features/lex.prf \
		/opt/qt-4.7.1/mkspecs/features/include_source_dir.prf \
		displayctl.pro
QMAKE_TARGET  = displayctl
DESTDIR       = 
TARGET        = displayctl

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_mainwindow.h ui_login.h ui_chainset.h ui_adjcoef.h ui_thresholdset.h ui_runningstatus.h ui_temperaturemonitor.h ui_faultcondition.h ui_hiscurve.h ui_passwordset.h ui_invalidset.h ui_dcset.h ui_keyboard.h ui_test.h ui_gainset.h ui_countdown.h ui_basicparaset.h ui_sysset.h ui_newadjdlg.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: displayctl.pro  /opt/qt-4.7.1/mkspecs/qws/linux-arm-g++/qmake.conf /opt/qt-4.7.1/mkspecs/common/g++.conf \
		/opt/qt-4.7.1/mkspecs/common/unix.conf \
		/opt/qt-4.7.1/mkspecs/common/linux.conf \
		/opt/qt-4.7.1/mkspecs/common/qws.conf \
		/opt/qt-4.7.1/mkspecs/qconfig.pri \
		/opt/qt-4.7.1/mkspecs/features/qt_functions.prf \
		/opt/qt-4.7.1/mkspecs/features/qt_config.prf \
		/opt/qt-4.7.1/mkspecs/features/exclusive_builds.prf \
		/opt/qt-4.7.1/mkspecs/features/default_pre.prf \
		/opt/qt-4.7.1/mkspecs/features/release.prf \
		/opt/qt-4.7.1/mkspecs/features/default_post.prf \
		/opt/qt-4.7.1/mkspecs/features/warn_on.prf \
		/opt/qt-4.7.1/mkspecs/features/qt.prf \
		/opt/qt-4.7.1/mkspecs/features/unix/thread.prf \
		/opt/qt-4.7.1/mkspecs/features/moc.prf \
		/opt/qt-4.7.1/mkspecs/features/resources.prf \
		/opt/qt-4.7.1/mkspecs/features/uic.prf \
		/opt/qt-4.7.1/mkspecs/features/yacc.prf \
		/opt/qt-4.7.1/mkspecs/features/lex.prf \
		/opt/qt-4.7.1/mkspecs/features/include_source_dir.prf \
		/opt/qt-4.7.1/lib/libQtGui.prl \
		/opt/qt-4.7.1/lib/libQtNetwork.prl \
		/opt/qt-4.7.1/lib/libQtCore.prl \
		/opt/qt-4.7.1/lib/libQt3Support.prl \
		/opt/qt-4.7.1/lib/libQtSql.prl \
		/opt/qt-4.7.1/lib/libQtXml.prl
	$(QMAKE) -o Makefile displayctl.pro
/opt/qt-4.7.1/mkspecs/common/g++.conf:
/opt/qt-4.7.1/mkspecs/common/unix.conf:
/opt/qt-4.7.1/mkspecs/common/linux.conf:
/opt/qt-4.7.1/mkspecs/common/qws.conf:
/opt/qt-4.7.1/mkspecs/qconfig.pri:
/opt/qt-4.7.1/mkspecs/features/qt_functions.prf:
/opt/qt-4.7.1/mkspecs/features/qt_config.prf:
/opt/qt-4.7.1/mkspecs/features/exclusive_builds.prf:
/opt/qt-4.7.1/mkspecs/features/default_pre.prf:
/opt/qt-4.7.1/mkspecs/features/release.prf:
/opt/qt-4.7.1/mkspecs/features/default_post.prf:
/opt/qt-4.7.1/mkspecs/features/warn_on.prf:
/opt/qt-4.7.1/mkspecs/features/qt.prf:
/opt/qt-4.7.1/mkspecs/features/unix/thread.prf:
/opt/qt-4.7.1/mkspecs/features/moc.prf:
/opt/qt-4.7.1/mkspecs/features/resources.prf:
/opt/qt-4.7.1/mkspecs/features/uic.prf:
/opt/qt-4.7.1/mkspecs/features/yacc.prf:
/opt/qt-4.7.1/mkspecs/features/lex.prf:
/opt/qt-4.7.1/mkspecs/features/include_source_dir.prf:
/opt/qt-4.7.1/lib/libQtGui.prl:
/opt/qt-4.7.1/lib/libQtNetwork.prl:
/opt/qt-4.7.1/lib/libQtCore.prl:
/opt/qt-4.7.1/lib/libQt3Support.prl:
/opt/qt-4.7.1/lib/libQtSql.prl:
/opt/qt-4.7.1/lib/libQtXml.prl:
qmake:  FORCE
	@$(QMAKE) -o Makefile displayctl.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/displayctl1.0.0 || $(MKDIR) .tmp/displayctl1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/displayctl1.0.0/ && $(COPY_FILE) --parents mainwindow.h logindlg.h adjcoefdlg.h chainsetdlg.h thresholdsetdlg.h gpiodatarecvthread.h gpiorw.h tempermonitorWidget.h faultcondWidget.h runningstatusWidget.h md5encode.h commmacro.h hiscurveWidget.h plotuserclass.h passwordsetdlg.h invalidsetdlg.h inifileparse.h dcsetdlg.h CANdatarw.h keyboarddlg.h hisCurvePlot.h mylineedit.h gainsetdlg.h judgeprotection.h countdownWidget.h basicparasetdlg.h syssetdlg.h spi.h datareadthread.h newadjdlg.h .tmp/displayctl1.0.0/ && $(COPY_FILE) --parents main.cpp mainwindow.cpp logindlg.cpp adjcoefdlg.cpp chainsetdlg.cpp thresholdsetdlg.cpp gpiodatarecvthread.cpp gpiorw.cpp tempermonitorWidget.cpp faultcondWidget.cpp runningstatusWidget.cpp md5encode.cpp hiscurveWidget.cpp plotuserclass.cpp passwordsetdlg.cpp invalidsetdlg.cpp inifileparse.cpp dcsetdlg.cpp CANdatarw.cpp keyboarddlg.cpp hisCurvePlot.cpp mylineedit.cpp gainsetdlg.cpp judgeprotection.cpp countdownWidget.cpp basicparasetdlg.cpp syssetdlg.cpp datareadthread.cpp newadjdlg.cpp .tmp/displayctl1.0.0/ && $(COPY_FILE) --parents mainwindow.ui login.ui chainset.ui adjcoef.ui thresholdset.ui runningstatus.ui temperaturemonitor.ui faultcondition.ui hiscurve.ui passwordset.ui invalidset.ui dcset.ui keyboard.ui test.ui gainset.ui countdown.ui basicparaset.ui sysset.ui newadjdlg.ui .tmp/displayctl1.0.0/ && (cd `dirname .tmp/displayctl1.0.0` && $(TAR) displayctl1.0.0.tar displayctl1.0.0 && $(COMPRESS) displayctl1.0.0.tar) && $(MOVE) `dirname .tmp/displayctl1.0.0`/displayctl1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/displayctl1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_mainwindow.cpp moc_logindlg.cpp moc_adjcoefdlg.cpp moc_chainsetdlg.cpp moc_thresholdsetdlg.cpp moc_tempermonitorWidget.cpp moc_faultcondWidget.cpp moc_runningstatusWidget.cpp moc_hiscurveWidget.cpp moc_plotuserclass.cpp moc_passwordsetdlg.cpp moc_invalidsetdlg.cpp moc_dcsetdlg.cpp moc_keyboarddlg.cpp moc_hisCurvePlot.cpp moc_mylineedit.cpp moc_gainsetdlg.cpp moc_countdownWidget.cpp moc_basicparasetdlg.cpp moc_syssetdlg.cpp moc_newadjdlg.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainwindow.cpp moc_logindlg.cpp moc_adjcoefdlg.cpp moc_chainsetdlg.cpp moc_thresholdsetdlg.cpp moc_tempermonitorWidget.cpp moc_faultcondWidget.cpp moc_runningstatusWidget.cpp moc_hiscurveWidget.cpp moc_plotuserclass.cpp moc_passwordsetdlg.cpp moc_invalidsetdlg.cpp moc_dcsetdlg.cpp moc_keyboarddlg.cpp moc_hisCurvePlot.cpp moc_mylineedit.cpp moc_gainsetdlg.cpp moc_countdownWidget.cpp moc_basicparasetdlg.cpp moc_syssetdlg.cpp moc_newadjdlg.cpp
moc_mainwindow.cpp: ui_mainwindow.h \
		mylineedit.h \
		logindlg.h \
		ui_login.h \
		commmacro.h \
		adjcoefdlg.h \
		ui_adjcoef.h \
		gpiorw.h \
		keyboarddlg.h \
		ui_keyboard.h \
		inifileparse.h \
		chainsetdlg.h \
		ui_chainset.h \
		thresholdsetdlg.h \
		ui_thresholdset.h \
		CANdatarw.h \
		gpiodatarecvthread.h \
		judgeprotection.h \
		tempermonitorWidget.h \
		ui_temperaturemonitor.h \
		countdownWidget.h \
		ui_countdown.h \
		faultcondWidget.h \
		ui_faultcondition.h \
		runningstatusWidget.h \
		ui_runningstatus.h \
		hiscurveWidget.h \
		ui_hiscurve.h \
		hisCurvePlot.h \
		plotuserclass.h \
		passwordsetdlg.h \
		ui_passwordset.h \
		gainsetdlg.h \
		ui_gainset.h \
		invalidsetdlg.h \
		ui_invalidset.h \
		dcsetdlg.h \
		ui_dcset.h \
		basicparasetdlg.h \
		ui_basicparaset.h \
		syssetdlg.h \
		ui_sysset.h \
		datareadthread.h \
		newadjdlg.h \
		mainwindow.h
	/opt/qt-4.7.1/bin/moc $(DEFINES) $(INCPATH) mainwindow.h -o moc_mainwindow.cpp

moc_logindlg.cpp: ui_login.h \
		commmacro.h \
		logindlg.h
	/opt/qt-4.7.1/bin/moc $(DEFINES) $(INCPATH) logindlg.h -o moc_logindlg.cpp

moc_adjcoefdlg.cpp: ui_adjcoef.h \
		mylineedit.h \
		commmacro.h \
		gpiorw.h \
		keyboarddlg.h \
		ui_keyboard.h \
		inifileparse.h \
		adjcoefdlg.h
	/opt/qt-4.7.1/bin/moc $(DEFINES) $(INCPATH) adjcoefdlg.h -o moc_adjcoefdlg.cpp

moc_chainsetdlg.cpp: ui_chainset.h \
		commmacro.h \
		gpiorw.h \
		inifileparse.h \
		chainsetdlg.h
	/opt/qt-4.7.1/bin/moc $(DEFINES) $(INCPATH) chainsetdlg.h -o moc_chainsetdlg.cpp

moc_thresholdsetdlg.cpp: ui_thresholdset.h \
		mylineedit.h \
		CANdatarw.h \
		commmacro.h \
		inifileparse.h \
		keyboarddlg.h \
		ui_keyboard.h \
		thresholdsetdlg.h
	/opt/qt-4.7.1/bin/moc $(DEFINES) $(INCPATH) thresholdsetdlg.h -o moc_thresholdsetdlg.cpp

moc_tempermonitorWidget.cpp: ui_temperaturemonitor.h \
		commmacro.h \
		tempermonitorWidget.h
	/opt/qt-4.7.1/bin/moc $(DEFINES) $(INCPATH) tempermonitorWidget.h -o moc_tempermonitorWidget.cpp

moc_faultcondWidget.cpp: ui_faultcondition.h \
		commmacro.h \
		faultcondWidget.h
	/opt/qt-4.7.1/bin/moc $(DEFINES) $(INCPATH) faultcondWidget.h -o moc_faultcondWidget.cpp

moc_runningstatusWidget.cpp: ui_runningstatus.h \
		commmacro.h \
		runningstatusWidget.h
	/opt/qt-4.7.1/bin/moc $(DEFINES) $(INCPATH) runningstatusWidget.h -o moc_runningstatusWidget.cpp

moc_hiscurveWidget.cpp: ui_hiscurve.h \
		hisCurvePlot.h \
		plotuserclass.h \
		hiscurveWidget.h
	/opt/qt-4.7.1/bin/moc $(DEFINES) $(INCPATH) hiscurveWidget.h -o moc_hiscurveWidget.cpp

moc_plotuserclass.cpp: plotuserclass.h
	/opt/qt-4.7.1/bin/moc $(DEFINES) $(INCPATH) plotuserclass.h -o moc_plotuserclass.cpp

moc_passwordsetdlg.cpp: ui_passwordset.h \
		passwordsetdlg.h
	/opt/qt-4.7.1/bin/moc $(DEFINES) $(INCPATH) passwordsetdlg.h -o moc_passwordsetdlg.cpp

moc_invalidsetdlg.cpp: ui_invalidset.h \
		mylineedit.h \
		inifileparse.h \
		commmacro.h \
		keyboarddlg.h \
		ui_keyboard.h \
		invalidsetdlg.h
	/opt/qt-4.7.1/bin/moc $(DEFINES) $(INCPATH) invalidsetdlg.h -o moc_invalidsetdlg.cpp

moc_dcsetdlg.cpp: keyboarddlg.h \
		ui_keyboard.h \
		commmacro.h \
		ui_dcset.h \
		mylineedit.h \
		dcsetdlg.h
	/opt/qt-4.7.1/bin/moc $(DEFINES) $(INCPATH) dcsetdlg.h -o moc_dcsetdlg.cpp

moc_keyboarddlg.cpp: ui_keyboard.h \
		commmacro.h \
		keyboarddlg.h
	/opt/qt-4.7.1/bin/moc $(DEFINES) $(INCPATH) keyboarddlg.h -o moc_keyboarddlg.cpp

moc_hisCurvePlot.cpp: plotuserclass.h \
		hisCurvePlot.h
	/opt/qt-4.7.1/bin/moc $(DEFINES) $(INCPATH) hisCurvePlot.h -o moc_hisCurvePlot.cpp

moc_mylineedit.cpp: mylineedit.h
	/opt/qt-4.7.1/bin/moc $(DEFINES) $(INCPATH) mylineedit.h -o moc_mylineedit.cpp

moc_gainsetdlg.cpp: ui_gainset.h \
		gainsetdlg.h
	/opt/qt-4.7.1/bin/moc $(DEFINES) $(INCPATH) gainsetdlg.h -o moc_gainsetdlg.cpp

moc_countdownWidget.cpp: ui_countdown.h \
		commmacro.h \
		countdownWidget.h
	/opt/qt-4.7.1/bin/moc $(DEFINES) $(INCPATH) countdownWidget.h -o moc_countdownWidget.cpp

moc_basicparasetdlg.cpp: ui_basicparaset.h \
		mylineedit.h \
		inifileparse.h \
		commmacro.h \
		keyboarddlg.h \
		ui_keyboard.h \
		basicparasetdlg.h
	/opt/qt-4.7.1/bin/moc $(DEFINES) $(INCPATH) basicparasetdlg.h -o moc_basicparasetdlg.cpp

moc_syssetdlg.cpp: ui_sysset.h \
		commmacro.h \
		gpiorw.h \
		keyboarddlg.h \
		ui_keyboard.h \
		inifileparse.h \
		basicparasetdlg.h \
		ui_basicparaset.h \
		mylineedit.h \
		syssetdlg.h
	/opt/qt-4.7.1/bin/moc $(DEFINES) $(INCPATH) syssetdlg.h -o moc_syssetdlg.cpp

moc_newadjdlg.cpp: commmacro.h \
		keyboarddlg.h \
		ui_keyboard.h \
		inifileparse.h \
		newadjdlg.h
	/opt/qt-4.7.1/bin/moc $(DEFINES) $(INCPATH) newadjdlg.h -o moc_newadjdlg.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_mainwindow.h ui_login.h ui_chainset.h ui_adjcoef.h ui_thresholdset.h ui_runningstatus.h ui_temperaturemonitor.h ui_faultcondition.h ui_hiscurve.h ui_passwordset.h ui_invalidset.h ui_dcset.h ui_keyboard.h ui_test.h ui_gainset.h ui_countdown.h ui_basicparaset.h ui_sysset.h ui_newadjdlg.h
compiler_uic_clean:
	-$(DEL_FILE) ui_mainwindow.h ui_login.h ui_chainset.h ui_adjcoef.h ui_thresholdset.h ui_runningstatus.h ui_temperaturemonitor.h ui_faultcondition.h ui_hiscurve.h ui_passwordset.h ui_invalidset.h ui_dcset.h ui_keyboard.h ui_test.h ui_gainset.h ui_countdown.h ui_basicparaset.h ui_sysset.h ui_newadjdlg.h
ui_mainwindow.h: mainwindow.ui \
		mylineedit.h
	/opt/qt-4.7.1/bin/uic mainwindow.ui -o ui_mainwindow.h

ui_login.h: login.ui
	/opt/qt-4.7.1/bin/uic login.ui -o ui_login.h

ui_chainset.h: chainset.ui
	/opt/qt-4.7.1/bin/uic chainset.ui -o ui_chainset.h

ui_adjcoef.h: adjcoef.ui \
		mylineedit.h
	/opt/qt-4.7.1/bin/uic adjcoef.ui -o ui_adjcoef.h

ui_thresholdset.h: thresholdset.ui \
		mylineedit.h
	/opt/qt-4.7.1/bin/uic thresholdset.ui -o ui_thresholdset.h

ui_runningstatus.h: runningstatus.ui
	/opt/qt-4.7.1/bin/uic runningstatus.ui -o ui_runningstatus.h

ui_temperaturemonitor.h: temperaturemonitor.ui
	/opt/qt-4.7.1/bin/uic temperaturemonitor.ui -o ui_temperaturemonitor.h

ui_faultcondition.h: faultcondition.ui
	/opt/qt-4.7.1/bin/uic faultcondition.ui -o ui_faultcondition.h

ui_hiscurve.h: hiscurve.ui
	/opt/qt-4.7.1/bin/uic hiscurve.ui -o ui_hiscurve.h

ui_passwordset.h: passwordset.ui
	/opt/qt-4.7.1/bin/uic passwordset.ui -o ui_passwordset.h

ui_invalidset.h: invalidset.ui \
		mylineedit.h
	/opt/qt-4.7.1/bin/uic invalidset.ui -o ui_invalidset.h

ui_dcset.h: dcset.ui \
		mylineedit.h
	/opt/qt-4.7.1/bin/uic dcset.ui -o ui_dcset.h

ui_keyboard.h: keyboard.ui
	/opt/qt-4.7.1/bin/uic keyboard.ui -o ui_keyboard.h

ui_test.h: test.ui
	/opt/qt-4.7.1/bin/uic test.ui -o ui_test.h

ui_gainset.h: gainset.ui
	/opt/qt-4.7.1/bin/uic gainset.ui -o ui_gainset.h

ui_countdown.h: countdown.ui
	/opt/qt-4.7.1/bin/uic countdown.ui -o ui_countdown.h

ui_basicparaset.h: basicparaset.ui \
		mylineedit.h
	/opt/qt-4.7.1/bin/uic basicparaset.ui -o ui_basicparaset.h

ui_sysset.h: sysset.ui
	/opt/qt-4.7.1/bin/uic sysset.ui -o ui_sysset.h

ui_newadjdlg.h: newadjdlg.ui \
		mylineedit.h
	/opt/qt-4.7.1/bin/uic newadjdlg.ui -o ui_newadjdlg.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_uic_clean 

####### Compile

main.o: main.cpp mainwindow.h \
		ui_mainwindow.h \
		mylineedit.h \
		logindlg.h \
		ui_login.h \
		commmacro.h \
		adjcoefdlg.h \
		ui_adjcoef.h \
		gpiorw.h \
		keyboarddlg.h \
		ui_keyboard.h \
		inifileparse.h \
		chainsetdlg.h \
		ui_chainset.h \
		thresholdsetdlg.h \
		ui_thresholdset.h \
		CANdatarw.h \
		gpiodatarecvthread.h \
		judgeprotection.h \
		tempermonitorWidget.h \
		ui_temperaturemonitor.h \
		countdownWidget.h \
		ui_countdown.h \
		faultcondWidget.h \
		ui_faultcondition.h \
		runningstatusWidget.h \
		ui_runningstatus.h \
		hiscurveWidget.h \
		ui_hiscurve.h \
		hisCurvePlot.h \
		plotuserclass.h \
		passwordsetdlg.h \
		ui_passwordset.h \
		gainsetdlg.h \
		ui_gainset.h \
		invalidsetdlg.h \
		ui_invalidset.h \
		dcsetdlg.h \
		ui_dcset.h \
		basicparasetdlg.h \
		ui_basicparaset.h \
		syssetdlg.h \
		ui_sysset.h \
		datareadthread.h \
		newadjdlg.h \
		md5encode.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mainwindow.o: mainwindow.cpp mainwindow.h \
		ui_mainwindow.h \
		mylineedit.h \
		logindlg.h \
		ui_login.h \
		commmacro.h \
		adjcoefdlg.h \
		ui_adjcoef.h \
		gpiorw.h \
		keyboarddlg.h \
		ui_keyboard.h \
		inifileparse.h \
		chainsetdlg.h \
		ui_chainset.h \
		thresholdsetdlg.h \
		ui_thresholdset.h \
		CANdatarw.h \
		gpiodatarecvthread.h \
		judgeprotection.h \
		tempermonitorWidget.h \
		ui_temperaturemonitor.h \
		countdownWidget.h \
		ui_countdown.h \
		faultcondWidget.h \
		ui_faultcondition.h \
		runningstatusWidget.h \
		ui_runningstatus.h \
		hiscurveWidget.h \
		ui_hiscurve.h \
		hisCurvePlot.h \
		plotuserclass.h \
		passwordsetdlg.h \
		ui_passwordset.h \
		gainsetdlg.h \
		ui_gainset.h \
		invalidsetdlg.h \
		ui_invalidset.h \
		dcsetdlg.h \
		ui_dcset.h \
		basicparasetdlg.h \
		ui_basicparaset.h \
		syssetdlg.h \
		ui_sysset.h \
		datareadthread.h \
		newadjdlg.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o mainwindow.cpp

logindlg.o: logindlg.cpp logindlg.h \
		ui_login.h \
		commmacro.h \
		md5encode.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o logindlg.o logindlg.cpp

adjcoefdlg.o: adjcoefdlg.cpp adjcoefdlg.h \
		ui_adjcoef.h \
		mylineedit.h \
		commmacro.h \
		gpiorw.h \
		keyboarddlg.h \
		ui_keyboard.h \
		inifileparse.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o adjcoefdlg.o adjcoefdlg.cpp

chainsetdlg.o: chainsetdlg.cpp chainsetdlg.h \
		ui_chainset.h \
		commmacro.h \
		gpiorw.h \
		inifileparse.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o chainsetdlg.o chainsetdlg.cpp

thresholdsetdlg.o: thresholdsetdlg.cpp thresholdsetdlg.h \
		ui_thresholdset.h \
		mylineedit.h \
		CANdatarw.h \
		commmacro.h \
		inifileparse.h \
		keyboarddlg.h \
		ui_keyboard.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o thresholdsetdlg.o thresholdsetdlg.cpp

gpiodatarecvthread.o: gpiodatarecvthread.cpp gpiodatarecvthread.h \
		gpiorw.h \
		commmacro.h \
		judgeprotection.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o gpiodatarecvthread.o gpiodatarecvthread.cpp

gpiorw.o: gpiorw.cpp gpiorw.h \
		commmacro.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o gpiorw.o gpiorw.cpp

tempermonitorWidget.o: tempermonitorWidget.cpp tempermonitorWidget.h \
		ui_temperaturemonitor.h \
		commmacro.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tempermonitorWidget.o tempermonitorWidget.cpp

faultcondWidget.o: faultcondWidget.cpp faultcondWidget.h \
		ui_faultcondition.h \
		commmacro.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o faultcondWidget.o faultcondWidget.cpp

runningstatusWidget.o: runningstatusWidget.cpp runningstatusWidget.h \
		ui_runningstatus.h \
		commmacro.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o runningstatusWidget.o runningstatusWidget.cpp

md5encode.o: md5encode.cpp md5encode.h \
		commmacro.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o md5encode.o md5encode.cpp

hiscurveWidget.o: hiscurveWidget.cpp hiscurveWidget.h \
		ui_hiscurve.h \
		hisCurvePlot.h \
		plotuserclass.h \
		commmacro.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o hiscurveWidget.o hiscurveWidget.cpp

plotuserclass.o: plotuserclass.cpp plotuserclass.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o plotuserclass.o plotuserclass.cpp

passwordsetdlg.o: passwordsetdlg.cpp passwordsetdlg.h \
		ui_passwordset.h \
		md5encode.h \
		commmacro.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o passwordsetdlg.o passwordsetdlg.cpp

invalidsetdlg.o: invalidsetdlg.cpp invalidsetdlg.h \
		ui_invalidset.h \
		mylineedit.h \
		inifileparse.h \
		commmacro.h \
		keyboarddlg.h \
		ui_keyboard.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o invalidsetdlg.o invalidsetdlg.cpp

inifileparse.o: inifileparse.cpp inifileparse.h \
		commmacro.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o inifileparse.o inifileparse.cpp

dcsetdlg.o: dcsetdlg.cpp dcsetdlg.h \
		keyboarddlg.h \
		ui_keyboard.h \
		commmacro.h \
		ui_dcset.h \
		mylineedit.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o dcsetdlg.o dcsetdlg.cpp

CANdatarw.o: CANdatarw.cpp CANdatarw.h \
		commmacro.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o CANdatarw.o CANdatarw.cpp

keyboarddlg.o: keyboarddlg.cpp keyboarddlg.h \
		ui_keyboard.h \
		commmacro.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o keyboarddlg.o keyboarddlg.cpp

hisCurvePlot.o: hisCurvePlot.cpp hisCurvePlot.h \
		plotuserclass.h \
		commmacro.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o hisCurvePlot.o hisCurvePlot.cpp

mylineedit.o: mylineedit.cpp mylineedit.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mylineedit.o mylineedit.cpp

gainsetdlg.o: gainsetdlg.cpp gainsetdlg.h \
		ui_gainset.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o gainsetdlg.o gainsetdlg.cpp

judgeprotection.o: judgeprotection.cpp judgeprotection.h \
		commmacro.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o judgeprotection.o judgeprotection.cpp

countdownWidget.o: countdownWidget.cpp countdownWidget.h \
		ui_countdown.h \
		commmacro.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o countdownWidget.o countdownWidget.cpp

basicparasetdlg.o: basicparasetdlg.cpp basicparasetdlg.h \
		ui_basicparaset.h \
		mylineedit.h \
		inifileparse.h \
		commmacro.h \
		keyboarddlg.h \
		ui_keyboard.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o basicparasetdlg.o basicparasetdlg.cpp

syssetdlg.o: syssetdlg.cpp syssetdlg.h \
		ui_sysset.h \
		commmacro.h \
		gpiorw.h \
		keyboarddlg.h \
		ui_keyboard.h \
		inifileparse.h \
		basicparasetdlg.h \
		ui_basicparaset.h \
		mylineedit.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o syssetdlg.o syssetdlg.cpp

datareadthread.o: datareadthread.cpp datareadthread.h \
		gpiorw.h \
		commmacro.h \
		judgeprotection.h \
		gpiodatarecvthread.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o datareadthread.o datareadthread.cpp

newadjdlg.o: newadjdlg.cpp newadjdlg.h \
		commmacro.h \
		keyboarddlg.h \
		ui_keyboard.h \
		inifileparse.h \
		ui_newadjdlg.h \
		mylineedit.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o newadjdlg.o newadjdlg.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

moc_logindlg.o: moc_logindlg.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_logindlg.o moc_logindlg.cpp

moc_adjcoefdlg.o: moc_adjcoefdlg.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_adjcoefdlg.o moc_adjcoefdlg.cpp

moc_chainsetdlg.o: moc_chainsetdlg.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_chainsetdlg.o moc_chainsetdlg.cpp

moc_thresholdsetdlg.o: moc_thresholdsetdlg.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_thresholdsetdlg.o moc_thresholdsetdlg.cpp

moc_tempermonitorWidget.o: moc_tempermonitorWidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_tempermonitorWidget.o moc_tempermonitorWidget.cpp

moc_faultcondWidget.o: moc_faultcondWidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_faultcondWidget.o moc_faultcondWidget.cpp

moc_runningstatusWidget.o: moc_runningstatusWidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_runningstatusWidget.o moc_runningstatusWidget.cpp

moc_hiscurveWidget.o: moc_hiscurveWidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_hiscurveWidget.o moc_hiscurveWidget.cpp

moc_plotuserclass.o: moc_plotuserclass.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_plotuserclass.o moc_plotuserclass.cpp

moc_passwordsetdlg.o: moc_passwordsetdlg.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_passwordsetdlg.o moc_passwordsetdlg.cpp

moc_invalidsetdlg.o: moc_invalidsetdlg.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_invalidsetdlg.o moc_invalidsetdlg.cpp

moc_dcsetdlg.o: moc_dcsetdlg.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_dcsetdlg.o moc_dcsetdlg.cpp

moc_keyboarddlg.o: moc_keyboarddlg.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_keyboarddlg.o moc_keyboarddlg.cpp

moc_hisCurvePlot.o: moc_hisCurvePlot.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_hisCurvePlot.o moc_hisCurvePlot.cpp

moc_mylineedit.o: moc_mylineedit.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mylineedit.o moc_mylineedit.cpp

moc_gainsetdlg.o: moc_gainsetdlg.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_gainsetdlg.o moc_gainsetdlg.cpp

moc_countdownWidget.o: moc_countdownWidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_countdownWidget.o moc_countdownWidget.cpp

moc_basicparasetdlg.o: moc_basicparasetdlg.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_basicparasetdlg.o moc_basicparasetdlg.cpp

moc_syssetdlg.o: moc_syssetdlg.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_syssetdlg.o moc_syssetdlg.cpp

moc_newadjdlg.o: moc_newadjdlg.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_newadjdlg.o moc_newadjdlg.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

